import { create } from 'zustand'

const translations = {
  en: {
    // Main Menu
    newGame: "NEW GAME",
    theLore: "THE LORE",
    controls: "CONTROLS",
    prepareToDie: "PREPARE TO DIE",
    language: "LANGUAGE",
    
    // Lore
    lore1_title: "THE AGE OF EMBERS",
    lore1_text: "Long ago, the First Flame was lit by the Titans — divine beings who forged the world from ash and void. Kingdoms rose, and humanity flourished beneath the golden glow of the Ashen Throne.",
    lore2_title: "THE SHATTERING",
    lore2_text: "Then came the Shattering. A curse spread across the land, and the dead refused to stay buried. The Ashen Throne fell silent. Its king — The Lord of Cinders — vanished into the deepest dark.",
    lore3_title: "YOUR CALLING",
    lore3_text: "You are an Ashen One — neither living nor dead. Fate has marked you with the Undead Brand. Only you can rekindle the First Flame... or let it die forever.",
    lore_continue: "CONTINUE →",
    lore_begin: "BEGIN JOURNEY",

    // HUD
    day: "☀️ Day",
    night: "🌙 Night",
    duskDawn: "🌅 Dusk/Dawn",
    hp: "HP",
    sp: "SP",
    mp: "MP",
    exp: "EXP",
    souls: "Souls",

    // Bonfire Menu
    restAtBonfire: "REST AT BONFIRE",
    leaveBonfire: "[ LEAVE BONFIRE ]",
    stats: "STATS",
    skills: "SKILLS",
    upgradeVigor: "Upgrade Vigor (+15 HP)",
    upgradeEndurance: "Upgrade Endurance (+15 SP)",
    upgradeStrength: "Upgrade Strength (+8 ATK)",
    upgradeAttunement: "Upgrade Attunement (+20 MP)",
    buyEstus: "Buy Estus Flask",
    currentMax: "Current max",
    expandsMax: "Expands max to",
    tier: "Tier",
    next: "Next",
    upgrade: "Upgrade",

    // Skills
    soulSlash_desc: "Wide arcanic slash — heavy damage in front.",
    flameBurst_desc: "Explodes a ring of fire around you.",
    voidStorm_desc: "(ULTIMATE) Void vortex obliterates nearby enemies.",
    skillUpgrade_sub: "+40% DMG, -2s Cooldown, -5 Mana Cost",

    // Systems
    nextDialog: "[Space / Click] Next Dialog",
    closeDialog: "[E] Close",
    respawn: "RESPAWN",
    quit: "QUIT TO MENU",
    paused: "PAUSED",
    resume: "RESUME",
    youDied: "YOU DIED",
    tryAgain: "TRY AGAIN",
    darknessClaims: "DARKNESS CLAIMS ANOTHER SOUL",
    talk: "Talk to",
    close: "Got it — Close",
    back: "BACK TO MENU",
    lore_begin: "BEGIN JOURNEY",
    lore_continue: "CONTINUE",
    ctrl_camera: "Rotate Camera",
    ctrl_zoom: "Zoom In / Out",
    ctrl_move: "Move Character",
    ctrl_sprint: "Sprint (drains stamina)",
    ctrl_dodge: "Dodge Roll",
    ctrl_light: "Light Attack",
    ctrl_heavy: "Heavy Attack",
    ctrl_parry: "Parry (block & stun)",
    ctrl_crouch: "Crouch (hold)",
    ctrl_estus: "Drink Estus Flask",
    ctrl_interact: "Interact (Bonfire / NPC)",
    ctrl_pause: "Pause / Unlock Mouse",
    ctrl_mouse: "Move Mouse",
    ctrl_scroll: "Scroll Wheel",
    dummyReward: "5 SOULS GAINED!",

    // NPC Names/Dialogs (Place names kept original)
    npc_raffus_name: "PEDAGANG RAFFUS",
    npc_raffus_1: "Welcome to Ashen Throne.",
    npc_raffus_2: "The Ashen Throne once burned with the First Flame...",
    npc_raffus_3: "Gather Souls — they are the currency of power here.",
    npc_raffus_4: "Rest at Bonfires to upgrade your body and skills.",
    npc_raffus_5: "Stay away from the Boss Arena if you are not ready!",

    npc_yorn_name: "GRAVEDIGGER YORN",
    npc_yorn_1: "This graveyard... I dug too many graves.",
    npc_yorn_2: "They rise again every night. Hollow and hungry.",
    npc_yorn_3: "If you face the Shadow Knights, dodge when they charge.",
    npc_yorn_4: "There's a bonfire deep east. Rest there before advancing.",

    npc_hunter_name: "FOREST HUNTER",
    npc_hunter_1: "The forest is not safe, stranger.",
    npc_hunter_2: "The Cursed Trees twist your sense of direction.",
    npc_hunter_3: "Berserkers lurk behind the mushroom circles.",
    npc_hunter_4: "Follow the glowing mushrooms to the bonfire path.",

    npc_nomad_name: "DESERT NOMAD",
    npc_nomad_1: "The sand swallows everything here.",
    npc_nomad_2: "I have walked for weeks. My canteen is dry.",
    npc_nomad_3: "The Armored Ones patrol the east dunes — stay west.",
    npc_nomad_4: "There was once an oasis... Titans consumed it.",

    npc_sailor_name: "STRANDED SAILOR",
    npc_sailor_1: "My ship broke on those rocks.",
    npc_sailor_2: "The beach looks peaceful but the tides bring monsters.",
    npc_sailor_3: "I've seen Ancient Ruins beyond the Palm Coast.",
    npc_sailor_4: "Whatever you do... don't enter the water at night.",

    npc_wizard_name: "FROST WIZARD",
    npc_wizard_1: "The cold here isn't natural.",
    npc_wizard_2: "A Titan's curse froze these fields centuries ago.",
    npc_wizard_3: "The Ice Crystals — touch them for warmth. Briefly.",
    npc_wizard_4: "Beyond the frost: the Ancient Ruins. And beyond that...",

    npc_scholar_name: "RUIN SCHOLAR",
    npc_scholar_1: "These ruins... I have dedicated my life to studying them.",
    npc_scholar_2: "The Titans built pillars to hold up the sky itself.",
    npc_scholar_3: "The Boss beyond: the Lord of Cinders himself.",
    npc_scholar_4: "Do not face him without full Estus Flasks and upgraded skills.",
    npc_scholar_5: "...You're going anyway, aren't you.",

    npc_aldric_name: "BLACKSMITH ALDRIC",
    npc_aldric_1: "I forge weapons from ashwood and old bones.",
    npc_aldric_2: "The Bonfire: it doesn't just warm — it strengthens.",
    npc_aldric_3: "Spend your Souls wisely at the flame. Do not hoard them.",
    npc_aldric_4: "The dead carry Souls of the living. Take them back.",

    npc_seryn_name: "LOREKEEPER SERYN",
    npc_seryn_1: "I remember the Age of Embers...",
    npc_seryn_2: "The First Flame was not found. It was *sacrificed*.",
    npc_seryn_3: "They say an Undead who rekindles the Flame becomes a Lord.",
    npc_seryn_4: "Or a cinder. It ends both ways in fire.",
    npc_seryn_5: "The choice was always yours, Ashen One.",

    npc_sentinel_name: "SENTINEL OF THE GATE",
    npc_sentinel_1: "You dare approach the Titan's Arena?",
    npc_sentinel_2: "Many Ashen Ones walked this path.",
    npc_sentinel_3: "None returned with their sanity intact.",
    npc_sentinel_4: "The Lord of Cinders will unmake everything you are.",
    npc_sentinel_5: "...I was once like you. Chosen. Brave. Foolish.",
  },
  id: {
    // Main Menu
    newGame: "MULAI BARU",
    theLore: "Kisah Dunia",
    controls: "KONTROL",
    prepareToDie: "BERSIAPLAH UNTUK MATI",
    language: "BAHASA",

    // Lore
    lore1_title: "ZAMAN BARA",
    lore1_text: "Dahulu kala, Api Pertama dinyalakan oleh para Titan — makhluk surgawi yang menempa dunia dari abu dan kehampaan. Kerajaan bangkit, dan kemanusiaan berkembang di bawah pancaran emas Ashen Throne.",
    lore2_title: "KEHANCURAN",
    lore2_text: "Kemudian terjadilah Kehancuran. Kutukan menyebar ke seluruh negeri, dan orang mati menolak untuk tetap dikuburkan. Ashen Throne menjadi sunyi. Rajanya — The Lord of Cinders — menghilang ke dalam kegelapan terdalam.",
    lore3_title: "PANGGILANMU",
    lore3_text: "Kau adalah Ashen One — tidak hidup maupun mati. Takdir telah menandaimu dengan Tanda Undead. Hanya kau yang bisa menyalakan kembali Api Pertama... atau membiarkannya mati selamanya.",
    lore_continue: "LANJUTKAN →",
    lore_begin: "MULAI PERJALANAN",

    // HUD
    day: "☀️ Siang",
    night: "🌙 Malam",
    duskDawn: "🌅 Senja/Fajar",
    hp: "HP",
    sp: "SP",
    mp: "MP",
    exp: "EXP",
    souls: "Souls",

    // Bonfire Menu
    restAtBonfire: "ISTIRAHAT DI BONFIRE",
    leaveBonfire: "[ TINGGALKAN BONFIRE ]",
    stats: "STATISTIK",
    skills: "KEAHLIAN",
    upgradeVigor: "Tingkatkan Vigor (+15 HP)",
    upgradeEndurance: "Tingkatkan Endurance (+15 SP)",
    upgradeStrength: "Tingkatkan Strength (+8 ATK)",
    upgradeAttunement: "Tingkatkan Attunement (+20 MP)",
    buyEstus: "Beli Estus Flask",
    currentMax: "Maks saat ini",
    expandsMax: "Tambah maks jadi",
    tier: "Tingkat",
    next: "Selanjutnya",
    upgrade: "Tingkatkan",

    // Skills
    soulSlash_desc: "Tebasan arcanic luas — kerusakan besar di depan.",
    flameBurst_desc: "Ledakan cincin api di sekitarmu.",
    voidStorm_desc: "(ULTIMATE) Pusaran hampa memusnahkan musuh di sekitar.",
    skillUpgrade_sub: "+40% DMG, -2s Cooldown, -5 Mana biaya",

    // Systems
    nextDialog: "[Spasi / Klik] Dialog Selanjutnya",
    closeDialog: "[E] Tutup",
    respawn: "BANGKIT LAGI",
    quit: "KE MENU UTAMA",
    paused: "BERHENTI SEJENAK",
    resume: "LANJUTKAN",
    youDied: "ANDA MATI",
    tryAgain: "COBA LAGI",
    darknessClaims: "KEGELAPAN MERENGGUT JIWAMU",
    talk: "Bicara dengan",
    close: "Mengerti — Tutup",
    back: "KEMBALI KE MENU",
    lore_begin: "MULAI PERJALANAN",
    lore_continue: "LANJUTKAN",
    ctrl_camera: "Putar Kamera",
    ctrl_zoom: "Perbesar / Perkecil",
    ctrl_move: "Gerakkan Karakter",
    ctrl_sprint: "Lari (kuras stamina)",
    ctrl_dodge: "Guling / Hindar",
    ctrl_light: "Tabasan Ringan",
    ctrl_heavy: "Tabasan Berat",
    ctrl_parry: "Paris (tangkis & stun)",
    ctrl_crouch: "Jongkok (tahan)",
    ctrl_estus: "Minum Estus Flask",
    ctrl_interact: "Interaksi (Bonfire / NPC)",
    ctrl_pause: "Jeda / Lepas Mouse",
    ctrl_mouse: "Gerakkan Mouse",
    ctrl_scroll: "Roda Scroll",
    dummyReward: "DAPAT 5 SOULS!",

    // NPC Names/Dialogs
    npc_raffus_name: "PEDAGANG RAFFUS",
    npc_raffus_1: "Selamat datang di Ashen Throne.",
    npc_raffus_2: "Ashen Throne dulu terbakar dengan Api Pertama...",
    npc_raffus_3: "Kumpulkan Souls — itu adalah mata uang kekuatan di sini.",
    npc_raffus_4: "Istirahat di Bonfire untuk meningkatkan tubuh dan keahlianmu.",
    npc_raffus_5: "Menjauhlah dari Boss Arena jika kau belum siap!",

    npc_yorn_name: "PENGGALI KUBUR YORN",
    npc_yorn_1: "Pemakaman ini... aku menggali terlalu banyak kuburan.",
    npc_yorn_2: "Mereka bangkit lagi setiap malam. Hampa dan lapar.",
    npc_yorn_3: "Jika kau menghadapi Shadow Knights, hindari saat mereka menyerang.",
    npc_yorn_4: "Ada api unggun di timur jauh. Istirahatlah di sana sebelum lanjut.",

    npc_hunter_name: "PEMBURU HUTAN",
    npc_hunter_1: "Hutan ini tidak aman, orang asing.",
    npc_hunter_2: "Pohon Terkutuk memutarbalikkan arah tujuanmu.",
    npc_hunter_3: "Berserker mengintai di balik lingkaran jamur.",
    npc_hunter_4: "Ikuti jamur yang bersinar ke jalur api unggun.",

    npc_nomad_name: "PENGLANA GURUN",
    npc_nomad_1: "Pasir menelan segalanya di sini.",
    npc_nomad_2: "Aku telah berjalan berminggu-minggu. Botol minumku kering.",
    npc_nomad_3: "Si Berzirah berpatroli di bukit pasir timur — tetaplah di barat.",
    npc_nomad_4: "Dahulu ada oase... para Titan melahapnya.",

    npc_sailor_name: "PELAUT TERDAMPAR",
    npc_sailor_1: "Kapalku hancur di bebatuan itu.",
    npc_sailor_2: "Pantai ini terlihat damai tapi pasang laut membawa monster.",
    npc_sailor_3: "Aku melihat Reruntuhan Kuno di balik Palm Coast.",
    npc_sailor_4: "Apapun yang kau lakukan... jangan masuk ke air saat malam.",

    npc_wizard_name: "PENYULAP ES",
    npc_wizard_1: "Dingin di sini tidak wajar.",
    npc_wizard_2: "Kutukan Titan membekukan ladang ini berabad-abad lalu.",
    npc_wizard_3: "Kristal Es — sentuh untuk kehangatan. Sebentar saja.",
    npc_wizard_4: "Di balik es: Reruntuhan Kuno. Dan di baliknya lagi...",

    npc_scholar_name: "PENELITI RERUNTUHAN",
    npc_scholar_1: "Reruntuhan ini... aku telah mendedikasikan hidupku untuk mempelajarinya.",
    npc_scholar_2: "Para Titan membangun pilar untuk menahan langit itu sendiri.",
    npc_scholar_3: "Bos di baliknya: sang Lord of Cinders sendiri.",
    npc_scholar_4: "Jangan hadapi dia tanpa Estus Flask penuh dan keahlian yang ditingkatkan.",
    npc_scholar_5: "...Kau tetap akan pergi, bukan.",

    npc_aldric_name: "PANDAI BESI ALDRIC",
    npc_aldric_1: "Aku menempa senjata dari kayu abu dan tulang tua.",
    npc_aldric_2: "Bonfire: tidak hanya menghangatkan — tapi memperkuat.",
    npc_aldric_3: "Gunakan Souls-mu dengan bijak di kobaran api. Jangan ditumpuk.",
    npc_aldric_4: "Orang mati membawa Souls orang hidup. Rebut kembali.",

    npc_seryn_name: "PENJAGA KISAH SERYN",
    npc_seryn_1: "Aku ingat Zaman Bara...",
    npc_seryn_2: "Api Pertama tidak ditemukan. Itu *dikorbankan*.",
    npc_seryn_3: "Kata mereka Undead yang menyalakan kembali Api akan menjadi Lord.",
    npc_seryn_4: "Atau menjadi abu. Keduanya berakhir dalam api.",
    npc_seryn_5: "Pilihan selalu ada di tanganmu, Ashen One.",

    npc_sentinel_name: "PENJAGA GERBANG",
    npc_sentinel_1: "Kau berani mendekati Titan's Arena?",
    npc_sentinel_2: "Banyak Ashen One berjalan di jalur ini.",
    npc_sentinel_3: "Tidak ada yang kembali dengan kewarasan yang utuh.",
    npc_sentinel_4: "Lord of Cinders akan menghancurkan segala jati dirimu.",
    npc_sentinel_5: "...Aku dulu sepertimu. Terpilih. Berani. Bodoh.",
  }
}

export const useLanguageStore = create((set) => ({
  language: 'en',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => {
    const lang = useLanguageStore.getState().language
    return translations[lang][key] || key
  }
}))
